version: "3.3"

services:
  # ----------------------------------------------------------------
  # Python
  # ----------------------------------------------------------------
  python:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_UID=1000
        - USER_GID=1000
    container_name: "python"
    tty: true
    volumes:
      - ./:/app
    ports:
      - 8000:8000
    entrypoint: /bin/sh
