[tool.poetry]
name = "app"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
jupyter = "^1.0.0"
ipykernel = "^6.29.4"

aiohttp = "^3.9.5"
flask = "^3.0.3"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
autopep8 = "2.0.0"
isort = "^5.13.2"
pytest = "^7.4.3"
mypy = "^1.8.0"
pyproject-flake8 = "5.0.4"

[tool.isort]
line_length = 119
multi_line_output = 3
include_trailing_comma = true
known_local_folder=['config',]

[tool.flake8]
max-line-length = 119
max-complexity = 18
ignore = "W293, W504, E111, E114, E402, E501,"
exclude = [".venv"]

[tool.autopep8]
max-line-length = 119
indent-size = 4
ignore = "E111, E114, E402, E501,"
aggressive = 3
exclude = ".venv"

[tool.mypy]
python_version = "3.8"
no_strict_optional = true
ignore_missing_imports = true
check_untyped_defs = true
exclude = ["/.venv/"]

[tool.pytest.ini_options]
testpaths = ["tests",]
filterwarnings = ["ignore::DeprecationWarning",]
addopts = ["--ignore=.venv"]
